# Generated by Django 5.0.6 on 2024-07-17 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NIDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='ID number must be between 10 and 15 digits.', regex='^\\d{10,15}$')])),
                ('id_name', models.CharField(max_length=30)),
                ('id_gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=100)),
                ('id_father_name', models.CharField(max_length=30)),
                ('id_mother_name', models.CharField(max_length=30)),
                ('id_date_of_birth', models.DateField()),
                ('id_address', models.CharField(max_length=300)),
                ('id_photo', models.ImageField(upload_to='nid_photos/')),
            ],
        ),
    ]
