# Generated by Django 5.0.6 on 2024-07-18 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeekModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrainModel',
            fields=[
                ('train_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Train.coachclass')),
                ('runs_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Train.weekmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Train.trainmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
