# Generated by Django 5.0.6 on 2024-07-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainmodel',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='trainmodel',
            name='runs_on',
        ),
        migrations.AddField(
            model_name='trainmodel',
            name='classes',
            field=models.ManyToManyField(blank=True, null=True, to='Train.coachclass'),
        ),
        migrations.AddField(
            model_name='trainmodel',
            name='runs_on',
            field=models.ManyToManyField(blank=True, null=True, to='Train.weekmodel'),
        ),
    ]
