# Generated by Django 5.0.6 on 2024-07-18 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Train', '0002_remove_trainmodel_classes_remove_trainmodel_runs_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={},
        ),
        migrations.RemoveField(
            model_name='station',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='station',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='station',
            name='order',
        ),
        migrations.RemoveField(
            model_name='station',
            name='train',
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Train.station')),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Train.trainmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
