# Generated by Django 5.0.6 on 2024-07-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_address_customuser_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default_username', max_length=30, unique=True),
        ),
    ]
