# Generated by Django 5.0.6 on 2024-07-18 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customuser_date_of_birth_and_more'),
    ]

    operations = [
    ]
